"""initial_schema_all_16_tables

Revision ID: ca98ebed8d42
Revises: 
Create Date: 2026-08-30 05:04:47.531487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca98ebed8d42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('apartment_id', sa.String(length=36), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('available', 'partially_occupied', 'fully_occupied', 'maintenance', 'closed', name='roomstatus'), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_rooms_apartment_id'), 'rooms', ['apartment_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'housing_administration', 'student_affairs', 'maintenance_officer', 'activity_officer', 'cleaning_officer', 'food_officer', 'sports_officer', 'system_administrator', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cleaning_cycles',
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('floor_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'optimizing', 'pending_approval', 'approved', 'active', 'completed', name='cleaningcyclestatus'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.create_index(op.f('ix_cleaning_cycles_floor_id'), 'cleaning_cycles', ['floor_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('unread', 'read', name='notificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('university', sa.String(length=200), nullable=False),
    sa.Column('major', sa.String(length=200), nullable=False),
    sa.Column('academic_status', sa.Enum('continuing', 'graduating', 'postgraduate', 'completed', name='academicstatus'), nullable=False),
    sa.Column('housing_status', sa.Enum('active', 'academic_break', 'suspended', 'terminated', name='housingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('ai_optimization_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm', sa.Enum('bfs', 'astar', name='aialgorithm'), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('fairness_score', sa.Float(), nullable=True),
    sa.Column('feasibility_rate', sa.Float(), nullable=True),
    sa.Column('nodes_expanded', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cycle_id'], ['cleaning_cycles.cycle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_ai_optimization_runs_cycle_id'), 'ai_optimization_runs', ['cycle_id'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'pending_documents', 'accepted', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_table('cleaning_assignments',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('task_description', sa.String(length=500), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'skipped', name='cleaningassignmentstatus'), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cleaning_cycles.cycle_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_cleaning_assignments_cycle_id'), 'cleaning_assignments', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_cleaning_assignments_student_id'), 'cleaning_assignments', ['student_id'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_review', 'resolved', 'closed', name='complaintstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('handled_by', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['handled_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaints_student_id'), 'complaints', ['student_id'], unique=False)
    op.create_table('disciplinary_cases',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('decision', sa.Enum('no_action', 'warning', 'temporary_suspension', 'termination', 'under_review', name='disciplinarydecision'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_disciplinary_cases_student_id'), 'disciplinary_cases', ['student_id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=True),
    sa.Column('problem_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_progress', 'resolved', 'closed', name='maintenancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('handled_by', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['handled_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_maintenance_requests_room_id'), 'maintenance_requests', ['room_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_student_id'), 'maintenance_requests', ['student_id'], unique=False)
    op.create_table('permission_requests',
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='permissionstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permission_requests_student_id'), 'permission_requests', ['student_id'], unique=False)
    op.create_table('room_assignments',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'ended', 'transferred', name='roomassignmentstatus'), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_room_assignments_room_id'), 'room_assignments', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_assignments_student_id'), 'room_assignments', ['student_id'], unique=False)
    op.create_table('student_absences',
    sa.Column('absence_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('absence_type', sa.Enum('permission', 'emergency', 'unauthorized', name='absencetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('absence_id')
    )
    op.create_index(op.f('ix_student_absences_student_id'), 'student_absences', ['student_id'], unique=False)
    op.create_table('student_status_history',
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status_type', sa.Enum('academic', 'housing', name='statustype'), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_student_status_history_student_id'), 'student_status_history', ['student_id'], unique=False)
    op.create_table('application_documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.Enum('national_id', 'university_id', 'academic_transcript', 'enrollment_certificate', 'medical_certificate', 'other', name='documenttype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_student_status_history_student_id'), table_name='student_status_history')
    op.drop_table('student_status_history')
    op.drop_index(op.f('ix_student_absences_student_id'), table_name='student_absences')
    op.drop_table('student_absences')
    op.drop_index(op.f('ix_room_assignments_student_id'), table_name='room_assignments')
    op.drop_index(op.f('ix_room_assignments_room_id'), table_name='room_assignments')
    op.drop_table('room_assignments')
    op.drop_index(op.f('ix_permission_requests_student_id'), table_name='permission_requests')
    op.drop_table('permission_requests')
    op.drop_index(op.f('ix_maintenance_requests_student_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_room_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_disciplinary_cases_student_id'), table_name='disciplinary_cases')
    op.drop_table('disciplinary_cases')
    op.drop_index(op.f('ix_complaints_student_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_cleaning_assignments_student_id'), table_name='cleaning_assignments')
    op.drop_index(op.f('ix_cleaning_assignments_cycle_id'), table_name='cleaning_assignments')
    op.drop_table('cleaning_assignments')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_ai_optimization_runs_cycle_id'), table_name='ai_optimization_runs')
    op.drop_table('ai_optimization_runs')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_cleaning_cycles_floor_id'), table_name='cleaning_cycles')
    op.drop_table('cleaning_cycles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rooms_apartment_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
